# Generated by Django 2.0.5 on 2018-05-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.IntegerField(unique=True)),
                ('osm_type', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
