# Generated by Django 2.0.5 on 2018-05-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0002_auto_20180503_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Court',
            new_name='Terrain',
        ),
    ]
