# Generated by Django 2.1.10 on 2019-07-07 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terrain', '0004_terrainimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerrainRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='terrain.Terrain')),
            ],
        ),
        migrations.AlterField(
            model_name='terrainimage',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='terrain.Terrain'),
        ),
    ]
